In [1]:
words = words = open('names.txt', 'r').read().splitlines()


In [2]:
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [3]:
len(words)

32033

In [4]:
min(len(w)for w in words)

2

In [5]:
max(len(w)for w in words)

15

In [6]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [7]:
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [8]:
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [9]:
from itertools import product
permutations=['..']+list(product('.',chars))+list(product(chars,chars))

In [10]:
len(permutations)

703

In [11]:

for w in words[:5]:
    chs = ["."]+list(w)+["."]
    for ch1,ch2,ch3 in zip(chs, chs[1:],chs[2:]): 
        print(ch1,ch2,ch3)

. e m
e m m
m m a
m a .
. o l
o l i
l i v
i v i
v i a
i a .
. a v
a v a
v a .
. i s
i s a
s a b
a b e
b e l
e l l
l l a
l a .
. s o
s o p
o p h
p h i
h i a
i a .


In [9]:
##one way to do it
# chars = sorted(list(set(''.join(words))))
# chars.insert(0,'.')
# index=-1
# stoii={}
# for i,s in enumerate(chars):
#     for j,z in enumerate(chars):
#         index+=1
#         stoii.update({s+z:index})
# sstoi=dict(sorted(stoii.items()))
# sitos = {i:s for s,i in sstoi.items()}

In [12]:
sstoi = {c[0]+c[1]:i for i, c in enumerate(permutations)}

In [13]:
len(sstoi)

703

In [14]:
sstoi

{'..': 0,
 '.a': 1,
 '.b': 2,
 '.c': 3,
 '.d': 4,
 '.e': 5,
 '.f': 6,
 '.g': 7,
 '.h': 8,
 '.i': 9,
 '.j': 10,
 '.k': 11,
 '.l': 12,
 '.m': 13,
 '.n': 14,
 '.o': 15,
 '.p': 16,
 '.q': 17,
 '.r': 18,
 '.s': 19,
 '.t': 20,
 '.u': 21,
 '.v': 22,
 '.w': 23,
 '.x': 24,
 '.y': 25,
 '.z': 26,
 'aa': 27,
 'ab': 28,
 'ac': 29,
 'ad': 30,
 'ae': 31,
 'af': 32,
 'ag': 33,
 'ah': 34,
 'ai': 35,
 'aj': 36,
 'ak': 37,
 'al': 38,
 'am': 39,
 'an': 40,
 'ao': 41,
 'ap': 42,
 'aq': 43,
 'ar': 44,
 'as': 45,
 'at': 46,
 'au': 47,
 'av': 48,
 'aw': 49,
 'ax': 50,
 'ay': 51,
 'az': 52,
 'ba': 53,
 'bb': 54,
 'bc': 55,
 'bd': 56,
 'be': 57,
 'bf': 58,
 'bg': 59,
 'bh': 60,
 'bi': 61,
 'bj': 62,
 'bk': 63,
 'bl': 64,
 'bm': 65,
 'bn': 66,
 'bo': 67,
 'bp': 68,
 'bq': 69,
 'br': 70,
 'bs': 71,
 'bt': 72,
 'bu': 73,
 'bv': 74,
 'bw': 75,
 'bx': 76,
 'by': 77,
 'bz': 78,
 'ca': 79,
 'cb': 80,
 'cc': 81,
 'cd': 82,
 'ce': 83,
 'cf': 84,
 'cg': 85,
 'ch': 86,
 'ci': 87,
 'cj': 88,
 'ck': 89,
 'cl': 90,
 'cm': 91

In [15]:
sitos = {i:s for s,i in sstoi.items()}

In [16]:
sitos

{0: '..',
 1: '.a',
 2: '.b',
 3: '.c',
 4: '.d',
 5: '.e',
 6: '.f',
 7: '.g',
 8: '.h',
 9: '.i',
 10: '.j',
 11: '.k',
 12: '.l',
 13: '.m',
 14: '.n',
 15: '.o',
 16: '.p',
 17: '.q',
 18: '.r',
 19: '.s',
 20: '.t',
 21: '.u',
 22: '.v',
 23: '.w',
 24: '.x',
 25: '.y',
 26: '.z',
 27: 'aa',
 28: 'ab',
 29: 'ac',
 30: 'ad',
 31: 'ae',
 32: 'af',
 33: 'ag',
 34: 'ah',
 35: 'ai',
 36: 'aj',
 37: 'ak',
 38: 'al',
 39: 'am',
 40: 'an',
 41: 'ao',
 42: 'ap',
 43: 'aq',
 44: 'ar',
 45: 'as',
 46: 'at',
 47: 'au',
 48: 'av',
 49: 'aw',
 50: 'ax',
 51: 'ay',
 52: 'az',
 53: 'ba',
 54: 'bb',
 55: 'bc',
 56: 'bd',
 57: 'be',
 58: 'bf',
 59: 'bg',
 60: 'bh',
 61: 'bi',
 62: 'bj',
 63: 'bk',
 64: 'bl',
 65: 'bm',
 66: 'bn',
 67: 'bo',
 68: 'bp',
 69: 'bq',
 70: 'br',
 71: 'bs',
 72: 'bt',
 73: 'bu',
 74: 'bv',
 75: 'bw',
 76: 'bx',
 77: 'by',
 78: 'bz',
 79: 'ca',
 80: 'cb',
 81: 'cc',
 82: 'cd',
 83: 'ce',
 84: 'cf',
 85: 'cg',
 86: 'ch',
 87: 'ci',
 88: 'cj',
 89: 'ck',
 90: 'cl',
 91: 'cm'

In [17]:
import torch
N = torch.zeros((len(sstoi),len(stoi)), dtype=torch.int32)
for w in words:
    chs = ".."+ w + "."
    for ch1,ch2,ch3 in zip(chs, chs[1:],chs[2:]):  
        ix1 = sstoi[ch1+ch2]
        ix2 = stoi[ch3]
        N[ix1,ix2]+= 1
        #print(ch1,ch2+ch3)
        #print(ix1,ix2)
print(N.sum(), N.shape)

tensor(228146) torch.Size([703, 27])


In [46]:
#for w in words[:5]:
#    chs = ["."]+list(w)+["."]
#    for ch1 , ch2,ch3 in zip(chs, chs[1:],chs[2:]):
#        ix1=stoi[ch1]
#        ix2 = stoi[ch2]
#        ix3 =stoi[ch3]
#        N[ix1,ix2,ix3]+= 1
        ##print(ch1 , ch2,ch3)

In [ ]:
# import matplotlib.pyplot as plt
# %matplotlib inline

# plt.figure(figsize=(16,16))
# plt.imshow(N, cmap='Blues')
# for i in range(729):
#     for j in range(729):
#         chstr = sitos[i] + sitos[j]
#         plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
#         plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
# plt.axis('off');

In [18]:
P = (N+1).float()
P /= P.sum(dim=1, keepdims=True)

In [19]:
P.shape

torch.Size([703, 27])

In [20]:
g = torch.Generator().manual_seed(2147483647)

for i in range(20):
    name = ".."
    while True:
        ss = name[-2:]
        i = sstoi[ss]
        sampled_i = int(torch.multinomial(P[i], 1, replacement=True, generator=g).item())
        sampled_s = itos[sampled_i]
        if sampled_i == 0:
            break
        name += sampled_s
    print(name)

..miq
..axx
..mereyannyaar
..knooraen
..el
..marviovania
..odarimalabelon
..hamirelslen
..elyn
..rae
..bra
..ceevlainacelonikaireil
..bech
..amilleia
..trutandennimsaby
..crewina
..lanoxvkyrina
..khine
..trise
..koberseberryslot


In [21]:
log_likelihood = 0.0
n = 0

for w in words:
    chs = '..' + w + '.'
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        ix1 = sstoi[ch1+ch2]
        ix2 = stoi[ch3]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
    #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

log_likelihood=tensor(-504653.)
nll=tensor(504653.)
2.2119739055633545


# With NN aproach

In [163]:
xs, ys = [], []
x1s ,x2s = [],[]
for w in words[:1]:
    chs = '..' + w + '.'
    for ch1, ch2, y in zip(chs, chs[1:], chs[2:]):
        x1s.append(stoi[ch1])
        x2s.append(stoi[ch2])
        xs.append([stoi[ch1], stoi[ch2]])
        ys.append(stoi[y])
        #print(ch1, ch2,y)
    
xs = torch.tensor(xs)
x1s = torch.tensor(x1s)
x2s = torch.tensor(x2s)
ys = torch.tensor(ys)
num = len(xs)

In [22]:
# create the training set of bigrams (x,y)
xs, ys = [], []

for w in words[:1]:
    chs = ".."+ w + "."
    for ch1,ch2,ch3 in zip(chs, chs[1:],chs[2:]):  
        ix1 = sstoi[ch1+ch2]
        ix2 = stoi[ch3]
        xs.append(ix1)
        ys.append(ix2)
        #print(ch1,ch2+ch3)
        #print(ix1,ix2)

    
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [23]:
xs

tensor([  0,   5, 143, 351, 339])

In [24]:
ys

tensor([ 5, 13, 13,  1,  0])

In [25]:
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes=len(sstoi)).float()
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [26]:
xenc.shape

torch.Size([5, 703])

In [27]:
xenc.dtype

torch.float32

In [28]:
W = torch.randn((len(sstoi), 27))
xenc @ W

tensor([[-0.7193,  1.5739, -0.7852, -0.5208, -0.3059,  1.1639,  0.0427, -0.0278,
         -0.1974, -2.6484, -0.4986, -0.2597, -1.2859,  0.8168,  2.6958, -0.0771,
          0.3434,  0.1427, -0.4941,  1.3033,  0.3560, -0.2224,  1.9778, -0.7546,
         -0.8619, -0.1740,  0.5863],
        [ 1.5332, -1.3735,  0.8764, -0.1706,  0.5675, -0.4027, -0.3813, -1.1717,
         -0.2672,  0.5818, -1.6911, -0.3497,  1.5037,  0.9940, -0.2293,  0.1433,
         -0.0402, -0.2905,  2.4515,  2.2222, -0.8576,  1.3291, -0.9423, -1.3883,
          1.3266,  1.2678,  1.1755],
        [ 0.0176,  0.8806, -0.2820,  1.1080, -1.1878,  1.2497, -0.2956,  0.8367,
          1.5718, -0.7211,  0.9488, -1.0821,  0.0662, -1.1454, -0.0824,  0.2345,
         -0.8377, -3.4768, -0.5782, -0.1995, -0.2894, -0.1001,  0.9250,  0.2167,
          0.1406,  0.4029, -0.1296],
        [-0.0370, -0.3498,  0.1606, -0.4824,  0.8537,  0.6077,  1.6702,  1.3631,
         -0.3320,  1.7083,  0.4424,  1.0263, -1.1094,  0.7876, -0.3246, -1.0478

In [29]:
(xenc @ W)[3,13]

tensor(0.7876)

In [30]:
(xenc[3]* W[:,13]).sum()

tensor(0.7876)

In [33]:
logits = (xenc @ W)
counts = logits.exp()
probs  = counts/counts.sum(1,keepdims=True)
probs

tensor([[0.0092, 0.0915, 0.0087, 0.0113, 0.0140, 0.0608, 0.0198, 0.0185, 0.0156,
         0.0013, 0.0115, 0.0146, 0.0052, 0.0429, 0.2811, 0.0176, 0.0267, 0.0219,
         0.0116, 0.0698, 0.0271, 0.0152, 0.1371, 0.0089, 0.0080, 0.0159, 0.0341],
        [0.0746, 0.0041, 0.0387, 0.0136, 0.0284, 0.0108, 0.0110, 0.0050, 0.0123,
         0.0288, 0.0030, 0.0114, 0.0724, 0.0435, 0.0128, 0.0186, 0.0155, 0.0120,
         0.1869, 0.1486, 0.0068, 0.0608, 0.0063, 0.0040, 0.0607, 0.0572, 0.0522],
        [0.0278, 0.0658, 0.0206, 0.0827, 0.0083, 0.0952, 0.0203, 0.0630, 0.1314,
         0.0133, 0.0705, 0.0092, 0.0292, 0.0087, 0.0251, 0.0345, 0.0118, 0.0008,
         0.0153, 0.0224, 0.0204, 0.0247, 0.0688, 0.0339, 0.0314, 0.0408, 0.0240],
        [0.0176, 0.0129, 0.0215, 0.0113, 0.0430, 0.0336, 0.0972, 0.0715, 0.0131,
         0.1010, 0.0285, 0.0511, 0.0060, 0.0402, 0.0132, 0.0064, 0.0071, 0.0158,
         0.0356, 0.0260, 0.0110, 0.0996, 0.0079, 0.0089, 0.0635, 0.1203, 0.0363],
        [0.0638, 0.0363,

In [35]:
probs[0].sum()

tensor(1.)

In [36]:
probs[0].shape

torch.Size([27])

In [37]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((len(sstoi), 27), generator=g)

In [38]:
xenc = F.one_hot(xs, num_classes=len(sstoi)).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) 

In [40]:
nlls = torch.zeros(5)
for i in range(5):
    # i-th bigram:
    x = xs[i].item() # input character index
    y = ys[i].item() # label character index
    print('--------')
    print(f'bigram example {i+1}: {sitos[x]}{itos[y]} (indexes {x},{y})')
    print('input to the neural net:', x)
    print('output probabilities from the neural net:', probs[i])
    print('label (actual next character):', y)
    p = probs[i, y]
    print('probability assigned by the net to the the correct character:', p.item())
    logp = torch.log(p)
    print('log likelihood:', logp.item())
    nll = -logp
    print('negative log likelihood:', nll.item())
    nlls[i] = nll

print('=========')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())

--------
bigram example 1: ..e (indexes 0,5)
input to the neural net: 0
output probabilities from the neural net: tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
label (actual next character): 5
probability assigned by the net to the the correct character: 0.01228625513613224
log likelihood: -4.399273872375488
negative log likelihood: 4.399273872375488
--------
bigram example 2: .em (indexes 5,13)
input to the neural net: 5
output probabilities from the neural net: tensor([0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
        0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
        0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472])
label (actual next character): 13
probability assigned by the net to the the correct character: 

In [47]:
xs, ys = [], []

for w in words:
    chs = ".."+ w + "."
    for ch1,ch2,ch3 in zip(chs, chs[1:],chs[2:]):  
        ix1 = sstoi[ch1+ch2]
        ix2 = stoi[ch3]
        xs.append(ix1)
        ys.append(ix2)
        #print(ch1,ch2+ch3)
        #print(ix1,ix2)

    
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((len(sstoi), 27), generator=g, requires_grad=True)

number of examples:  228146


In [104]:
for k in range(100):
  
    # forward pass
    xenc = F.one_hot(xs, num_classes=len(sstoi)).float() # input to the network: one-hot encoding
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
    loss = -probs[torch.arange(num), ys].log().mean() + 0.01*(W**2).mean()
    print(loss.item())

    # backward pass
    W.grad = None # set to zero the gradient
    loss.backward()

    # update
    W.data += -50 * W.grad

2.2405593395233154
2.240535259246826
2.2405107021331787
2.2404866218566895
2.240462303161621
2.240438222885132
2.2404141426086426
2.240389823913574
2.240365982055664
2.240341901779175
2.2403178215026855
2.2402939796447754
2.240269899368286
2.240246295928955
2.240222454071045
2.2401986122131348
2.2401747703552246
2.2401511669158936
2.2401273250579834
2.2401039600372314
2.2400803565979004
2.2400565147399902
2.240032911300659
2.2400095462799072
2.239985942840576
2.239962577819824
2.2399392127990723
2.2399158477783203
2.2398924827575684
2.2398688793182373
2.2398457527160645
2.2398226261138916
2.2397994995117188
2.239776372909546
2.239753007888794
2.2397301197052
2.2397067546844482
2.2396838665008545
2.2396609783172607
2.239638090133667
2.239614963531494
2.2395923137664795
2.239569664001465
2.239546537399292
2.2395236492156982
2.2395009994506836
2.239478349685669
2.239455461502075
2.2394330501556396
2.239410400390625
2.2393879890441895
2.2393651008605957
2.2393429279327393
2.239320039749145

In [105]:
g = torch.Generator().manual_seed(2147483647)

for i in range(20):
  
    out = []
    name = ".."
    while True:

    # ----------
    # BEFORE:
    #p = P[ix]
    # ----------
    # NOW:
        ss = name[-2:]
        i = sstoi[ss]
        xenc = F.one_hot(torch.tensor(i), num_classes=len(sstoi)).float()
        #print(xenc.shape)
        logits = xenc @ W # predict log-counts
        #print(logits.shape)
        counts = logits.exp() # counts, equivalent to N
        #print(counts)
        p = counts / counts.sum() # probabilities for next character
        # ----------

        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        name += itos[int(ix)]
        if ix == 0:
            break
    print(name)
    #print(''.join(out))

..mir.
..axx.
..mereyannyaar.
..knooraen.
..el.
..marviovania.
..odarimalabelon.
..hamirelsngfjdlyn.
..rae.
..bra.
..ceevi.
..isemarrisleemikh.
..bech.
..amilleia.
..trutchemiriouchya.
..tavina.
..lanoxtotten.
..denellaymlxiber.
..fria.
..kirvvpsratten.
